[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  01:40:48Z

App            Version  Status   Scale  Charm        Channel  Rev  Address         Exposed  Message
config-server           active       1  mongodb-k8s  6/edge    50  10.152.183.155  no       Primary
mongos-k8s              waiting      1  mongos-k8s              0  10.152.183.157  no       installing agent
shard0                  active       1  mongodb-k8s  6/edge    50  10.152.183.229  no       Primary

Unit              Workload     Agent      Address       Ports  Message
config-server/0*  active       idle       10.1.212.142         Primary
mongos-k8s/0*     maintenance  executing  10.1.212.136         starting mongos
shard0/0*         active       idle       10.1.212.141         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:29:36 ERROR unit.config-server/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-config-server-0/charm/./src/charm.py", line 1555, in <module>
    main(MongoDBCharm)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-config-server-0/charm/./src/charm.py", line 551, in _on_mongod_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-config-server-0/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mongod" (cannot start service: exited quickly with code 1)
----- Logs from task 1 -----
2024-08-23T01:29:36Z INFO Most recent service output:
    {"t":{"$date":"2024-08-23T01:29:36.586Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"-","msg":"Applied --setParameter options","attr":{"serverParameters":{"processUmask":{"default":63,"value":31}}}}
    {"t":{"$date":"2024-08-23T01:29:36.586Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":38,"codeName":"FileNotOpen","errmsg":"Can't initialize rotatable log file :: caused by :: Failed to open /var/log/mongodb/mongodb.log"}}}
2024-08-23T01:29:36Z ERROR cannot start service: exited quickly with code 1
-----
unit-config-server-0: 01:29:36 ERROR juju.worker.uniter.operation hook "mongod-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-config-server-0: 01:29:36 ERROR juju.worker.uniter pebble poll failed for container "mongod": failed to send pebble-ready event: hook failed

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...