[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mongos-k8s/0 [idle] active: 
  data-integrator/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.5.3    unsupported  01:39:24Z

App              Version  Status  Scale  Charm            Channel        Rev  Address         Exposed  Message
application               active      1  application                       0                  no       
config-server             active      1  mongodb-k8s      6/edge          56  10.152.183.224  no       
data-integrator           active      1  data-integrator  latest/stable   41  10.152.183.111  no       
mongos-k8s                active      1  mongos-k8s                        0  10.152.183.57   no       
shard0                    active      1  mongodb-k8s      6/edge          56  10.152.183.253  no       Primary

Unit                Workload  Agent  Address     Ports  Message
application/0*      active    idle                      
config-server/0*    active    idle   10.1.76.13         
data-integrator/0*  active    idle   10.1.76.17         
mongos-k8s/0*       active    idle   10.1.76.8          
shard0/0*           active    idle   10.1.76.14         Primary

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

unit-config-server-0: 01:31:40 ERROR unit.config-server/0.juju-log config-server:4: Failed to add shard shard0 to the config server, error=OperationFailure("Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1728610299, 1), 'signature': {'hash': b'g\\xac\\x8d\\xd1e\\xea+c\\x1az\\xd5Y\\xd3\\x14\\x9e\\xbf\\x00\\xc3\\xd3\\xf5', 'keyId': 7424324478395482137}}, 'operationTime': Timestamp(1728610299, 1)}")
unit-config-server-0: 01:31:40 ERROR unit.config-server/0.juju-log config-server:4: shard0 shard does not have the same auth as the config server.
unit-mongos-k8s-0: 01:38:08 ERROR unit.mongos-k8s/0.juju-log External configuration: nonsensical-setting for expose-external is not valid, should be one of: ['none', 'nodeport']

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...