{"uid":"a5bf56d225a71ac0","name":"test_mongos_external_connections","fullName":"tests.integration.client_relations.test_external_client_relations#test_mongos_external_connections","historyId":"86e5caa05a50da55798fb53d7ba18b1d","time":{"start":1727400986890,"stop":1727401004388,"duration":17498},"description":"Tests that mongos is accessible externally.","descriptionHtml":"<p>Tests that mongos is accessible externally.</p>\n","status":"broken","statusMessage":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727401004, 2), 'signature': {'hash': b'\\xc5\\xa3\\xa2qE|\\xb2\\xae\\x84\\x0b\\xbd\\xb1p\\xd6\\xe9\\x88\\xc0\\xe7\\x0c@', 'keyId': 7419129182875025433}}, 'operationTime': Timestamp(1727401004, 2)}","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/tests/integration/client_relations/test_external_client_relations.py\", line 50, in test_mongos_external_connections\n    await assert_all_unit_node_ports_available(ops_test)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/tests/integration/client_relations/helpers.py\", line 117, in assert_all_unit_node_ports_available\n    assert await is_external_mongos_client_reachable(\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/tests/integration/client_relations/helpers.py\", line 132, in is_external_mongos_client_reachable\n    external_mongos_client.admin.command(\"usersInfo\")\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/_csot.py\", line 108, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/database.py\", line 893, in command\n    with self.__client._conn_for_reads(read_preference, session, operation=command_name) as (\n  File \"/usr/lib/python3.10/contextlib.py\", line 135, in __enter__\n    return next(self.gen)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1357, in _conn_from_server\n    with self._checkout(server, session) as conn:\n  File \"/usr/lib/python3.10/contextlib.py\", line 135, in __enter__\n    return next(self.gen)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1266, in _checkout\n    with server.checkout(handler=err_handler) as conn:\n  File \"/usr/lib/python3.10/contextlib.py\", line 135, in __enter__\n    return next(self.gen)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1767, in checkout\n    conn = self._get_conn(checkout_started_time, handler=handler)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1926, in _get_conn\n    conn = self.connect(handler=handler)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1729, in connect\n    conn.authenticate()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1099, in authenticate\n    auth.authenticate(creds, self, reauthenticate=reauthenticate)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/auth.py\", line 656, in authenticate\n    auth_func(credentials, conn)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/auth.py\", line 560, in _authenticate_default\n    return _authenticate_scram(credentials, conn, \"SCRAM-SHA-1\")\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/auth.py\", line 299, in _authenticate_scram\n    res = conn.command(source, cmd)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/helpers.py\", line 342, in inner\n    return func(*args, **kwargs)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 989, in command\n    return command(\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/network.py\", line 212, in command\n    helpers._check_command_response(\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/helpers.py\", line 248, in _check_command_response\n    raise OperationFailure(errmsg, code, response, max_wire_version)\npymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727401004, 2), 'signature': {'hash': b'\\xc5\\xa3\\xa2qE|\\xb2\\xae\\x84\\x0b\\xbd\\xb1p\\xd6\\xe9\\x88\\xc0\\xe7\\x0c@', 'keyId': 7419129182875025433}}, 'operationTime': Timestamp(1727401004, 2)}","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1727400583206,"stop":1727400583206,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1727400583207,"stop":1727400583207,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1727400583207,"stop":1727400583437,"duration":230},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1727400986889,"stop":1727400986889,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Tests that mongos is accessible externally.","status":"broken","statusMessage":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727401004, 2), 'signature': {'hash': b'\\xc5\\xa3\\xa2qE|\\xb2\\xae\\x84\\x0b\\xbd\\xb1p\\xd6\\xe9\\x88\\xc0\\xe7\\x0c@', 'keyId': 7419129182875025433}}, 'operationTime': Timestamp(1727401004, 2)}","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 848, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 831, in _runtest_for\n    yield\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 879, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/tests/integration/client_relations/test_external_client_relations.py\", line 50, in test_mongos_external_connections\n    await assert_all_unit_node_ports_available(ops_test)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/tests/integration/client_relations/helpers.py\", line 117, in assert_all_unit_node_ports_available\n    assert await is_external_mongos_client_reachable(\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/tests/integration/client_relations/helpers.py\", line 132, in is_external_mongos_client_reachable\n    external_mongos_client.admin.command(\"usersInfo\")\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/_csot.py\", line 108, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/database.py\", line 893, in command\n    with self.__client._conn_for_reads(read_preference, session, operation=command_name) as (\n  File \"/usr/lib/python3.10/contextlib.py\", line 135, in __enter__\n    return next(self.gen)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1357, in _conn_from_server\n    with self._checkout(server, session) as conn:\n  File \"/usr/lib/python3.10/contextlib.py\", line 135, in __enter__\n    return next(self.gen)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1266, in _checkout\n    with server.checkout(handler=err_handler) as conn:\n  File \"/usr/lib/python3.10/contextlib.py\", line 135, in __enter__\n    return next(self.gen)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1767, in checkout\n    conn = self._get_conn(checkout_started_time, handler=handler)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1926, in _get_conn\n    conn = self.connect(handler=handler)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1729, in connect\n    conn.authenticate()\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 1099, in authenticate\n    auth.authenticate(creds, self, reauthenticate=reauthenticate)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/auth.py\", line 656, in authenticate\n    auth_func(credentials, conn)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/auth.py\", line 560, in _authenticate_default\n    return _authenticate_scram(credentials, conn, \"SCRAM-SHA-1\")\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/auth.py\", line 299, in _authenticate_scram\n    res = conn.command(source, cmd)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/helpers.py\", line 342, in inner\n    return func(*args, **kwargs)\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/pool.py\", line 989, in command\n    return command(\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/network.py\", line 212, in command\n    helpers._check_command_response(\n  File \"/home/runner/work/mongos-k8s-operator/mongos-k8s-operator/.tox/integration/lib/python3.10/site-packages/pymongo/helpers.py\", line 248, in _check_command_response\n    raise OperationFailure(errmsg, code, response, max_wire_version)\npymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727401004, 2), 'signature': {'hash': b'\\xc5\\xa3\\xa2qE|\\xb2\\xae\\x84\\x0b\\xbd\\xb1p\\xd6\\xe9\\x88\\xc0\\xe7\\x0c@', 'keyId': 7419129182875025433}}, 'operationTime': Timestamp(1727401004, 2)}","steps":[],"attachments":[{"uid":"d9b53e720270257b","name":"log","source":"d9b53e720270257b.txt","type":"text/plain","size":91}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1727401004390,"stop":1727401004390,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1727401004401,"stop":1727401004732,"duration":331},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1727401004732,"stop":1727401004733,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1727401004733,"stop":1727401004733,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1727401004733,"stop":1727401004733,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.client_relations"},{"name":"suite","value":"test_external_client_relations"},{"name":"host","value":"fv-az692-464"},{"name":"thread","value":"13160-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.client_relations.test_external_client_relations"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"525ecf73f3646f94","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":15,"skipped":0,"passed":12,"unknown":0,"total":27},"items":[{"uid":"ab0b50e2336f5dc5","reportUrl":"../280//#testresult/ab0b50e2336f5dc5","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727314578, 1), 'signature': {'hash': b'd\\x08<\\xdf\\xef\\xeb\\x05.\\x05\\xa1\\x86\\x8fy\\xf3$)Ygr\\xaa', 'keyId': 7418758084815749145}}, 'operationTime': Timestamp(1727314578, 1)}","time":{"start":1727314561221,"stop":1727314578818,"duration":17597}},{"uid":"692e050b32cf0e2b","reportUrl":"../279//#testresult/692e050b32cf0e2b","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727228184, 1), 'signature': {'hash': b'\\xbe\\xb2\\xf5S\\x19\\xca\\xabxf\\xa1\\x92 _\\x11\\x97J?\\x99\\xc7\\n', 'keyId': 7418387111310524441}}, 'operationTime': Timestamp(1727228184, 1)}","time":{"start":1727228166851,"stop":1727228184881,"duration":18030}},{"uid":"5b067ccca578524f","reportUrl":"../278//#testresult/5b067ccca578524f","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727141802, 3), 'signature': {'hash': b\"\\x0eH\\x1a7\\x0e\\xd8=h\\x99\\xb3\\xdfy\\xcd4\\xda\\xee\\xd7'\\x1a5\", 'keyId': 7418015923056934937}}, 'operationTime': Timestamp(1727141802, 3)}","time":{"start":1727141783569,"stop":1727141803441,"duration":19872}},{"uid":"ca629542c6faefc1","reportUrl":"../275//#testresult/ca629542c6faefc1","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1727055389, 3), 'signature': {'hash': b'\\ra\\xf6\\x1b.\\x0e\\xcf\\x95\\n\\xe6\\xa2\\xf5\\xc4\"u\\x88Y\\xf6e\\x81', 'keyId': 7417644902307069977}}, 'operationTime': Timestamp(1727055389, 3)}","time":{"start":1727055370018,"stop":1727055390115,"duration":20097}},{"uid":"500a44484d0ef7aa","reportUrl":"../274//#testresult/500a44484d0ef7aa","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726968990, 2), 'signature': {'hash': b'\\xc8\\xf1y\\xc8l/\\x0e\\xa8\"c\\x7f\\',\\x8c\\xb0h\\x10\\xdc\\x87M', 'keyId': 7417273778477989913}}, 'operationTime': Timestamp(1726968990, 2)}","time":{"start":1726968969596,"stop":1726968990314,"duration":20718}},{"uid":"fa9bdb82bd21bee2","reportUrl":"../273//#testresult/fa9bdb82bd21bee2","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726882538, 3), 'signature': {'hash': b'|\\xd0\\xb1@q\\x8ai\\xefU\\n2\\x15u\\x96\\x106\\t\\xd8\\x80n', 'keyId': 7416902607404269593}}, 'operationTime': Timestamp(1726882538, 3)}","time":{"start":1726882518665,"stop":1726882538920,"duration":20255}},{"uid":"5dacc749ed34516e","reportUrl":"../272//#testresult/5dacc749ed34516e","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726796156, 4), 'signature': {'hash': b'3\\x83q1P\\xc5K\\x87\\xd0\\x0b\\x98\\x93\\xbf\\xcc\\x9c\\xf5q=\\xa7x', 'keyId': 7416531599539306521}}, 'operationTime': Timestamp(1726796156, 4)}","time":{"start":1726796136942,"stop":1726796157150,"duration":20208}},{"uid":"64c8307e95db7d18","reportUrl":"../270//#testresult/64c8307e95db7d18","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726709765, 2), 'signature': {'hash': b'\\x86C\\xbffs^\\x84F\\xd40\\xa3\\xab\\xa8\\xde\\x94\\xd1\\x82j\\xc6\\x00', 'keyId': 7416160505774997529}}, 'operationTime': Timestamp(1726709765, 2)}","time":{"start":1726709744299,"stop":1726709765628,"duration":21329}},{"uid":"f56b2fc7c1f9508d","reportUrl":"../269//#testresult/f56b2fc7c1f9508d","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726623408, 5), 'signature': {'hash': b'\\x97\\x1bm/C4\\xacC\\xec%gr\\xe9<{\\xb3\\x18\\x86\\r\\x91', 'keyId': 7415789480730165257}}, 'operationTime': Timestamp(1726623408, 5)}","time":{"start":1726623388617,"stop":1726623408805,"duration":20188}},{"uid":"9e991b3a45a6e4cc","reportUrl":"../264//#testresult/9e991b3a45a6e4cc","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726450598, 1), 'signature': {'hash': b'\\x85=\\xa1\\x18\\xbb\\x98-\\xb3\\xb6\\xf1\\x84uf\\x19\\x89\\xd2\\x82\\xebz_', 'keyId': 7415047318971351065}}, 'operationTime': Timestamp(1726450598, 1)}","time":{"start":1726450581469,"stop":1726450598863,"duration":17394}},{"uid":"cbb9207e63ec4c4e","reportUrl":"../263//#testresult/cbb9207e63ec4c4e","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726364130, 2), 'signature': {'hash': b'\\x87\\x1b\\xd4\\xe2\\x870\\xe6\\xd2\\xb8\\x1a\\xd4\\x14)\\xa9?W\\\\\\xfe\\xfa\\xd5', 'keyId': 7414676238091943961}}, 'operationTime': Timestamp(1726364130, 2)}","time":{"start":1726364111707,"stop":1726364131417,"duration":19710}},{"uid":"2f56dbcabaea993","reportUrl":"../262//#testresult/2f56dbcabaea993","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726277726, 2), 'signature': {'hash': b'f\\xf7\\xeb\\xc3\\xc2\\x15\\xfaQ\\x15*\\x97\\x10W\\xea|\\xbb\\x87\\xbe>\\xc3', 'keyId': 7414305084198092825}}, 'operationTime': Timestamp(1726277726, 2)}","time":{"start":1726277706739,"stop":1726277727253,"duration":20514}},{"uid":"229adbe438797119","reportUrl":"../259//#testresult/229adbe438797119","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726191330, 1), 'signature': {'hash': b'\\xcb\\xce\\xa0\\x14\\x8d+z\\x9d\\x9a\\t\\x93)$\\x89\\xc1\\xeb\\x9a\\xde\\x99\\x98', 'keyId': 7413933900239470617}}, 'operationTime': Timestamp(1726191330, 1)}","time":{"start":1726191314192,"stop":1726191331722,"duration":17530}},{"uid":"967cd0ec3a87ba1e","reportUrl":"../251//#testresult/967cd0ec3a87ba1e","status":"broken","statusDetails":"pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed', '$clusterTime': {'clusterTime': Timestamp(1726104940, 1), 'signature': {'hash': b'5\\x10e\\x96\\x91\\x0c\\xbekH\\xd2j\\x0c\\x11\\x19YS6$o\\x8c', 'keyId': 7413562858014769177}}, 'operationTime': Timestamp(1726104940, 1)}","time":{"start":1726104923609,"stop":1726104941158,"duration":17549}},{"uid":"5154a4921cb30605","reportUrl":"../245//#testresult/5154a4921cb30605","status":"passed","time":{"start":1726018491030,"stop":1726018519510,"duration":28480}},{"uid":"f737d0ae365ae05c","reportUrl":"../244//#testresult/f737d0ae365ae05c","status":"passed","time":{"start":1725932184678,"stop":1725932202137,"duration":17459}},{"uid":"c51a9d3f9a15c596","reportUrl":"../242//#testresult/c51a9d3f9a15c596","status":"passed","time":{"start":1725845782042,"stop":1725845816172,"duration":34130}},{"uid":"e41e2b9e6a5a6e5c","reportUrl":"../241//#testresult/e41e2b9e6a5a6e5c","status":"passed","time":{"start":1725759354474,"stop":1725759371995,"duration":17521}},{"uid":"48c0fc87108f0d3","reportUrl":"../240//#testresult/48c0fc87108f0d3","status":"passed","time":{"start":1725673257682,"stop":1725673277838,"duration":20156}},{"uid":"5d3216f3f435b33d","reportUrl":"../238//#testresult/5d3216f3f435b33d","status":"passed","time":{"start":1725586636319,"stop":1725586656237,"duration":19918}}]},"tags":["asyncio","abort_on_fail","group(1)"]},"source":"a5bf56d225a71ac0.json","parameterValues":[]}